[package]
name = "rnd"
version = "0.1.0"
authors = ["Gerold <gkuehne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
chrono = "0.4"
rand_xoshiro = "0.4"
rand_core = "0.5"